version: '3'

services:

  geoserver:
    image: thiras/geoserver
    build:
      context: docker-geoserver
      args:
        - ORACLE_JDk=true
    links:
      - postgis
    ports:
      - "8080:8080"
    volumes:
      - ./docker-geoserver/resources:/opt/geoserver/data_dir
    depends_on:
      - postgis

  postgis:
    image: thiras/postgis
    build:
      context: docker-postgis
    environment:
      POSTGRES_PASSWORD: 123456
    links:
      - pgadmin
    volumes:
      - ./db:/var/lib/postgresql
    user: postgres

  pgadmin:
    image: fenglc/pgadmin4
    ports:
      - "5050:5050"
