version: '3.2'

services:

  geoserver:
    image: thiras/geoserver
    build:
      context: docker-geoserver
      args:
        - ORACLE_JDk=true
    links:
      - postgis
    ports:
      - "8085:8080"
    volumes:
      - geo_data:/opt/geoserver/data_dir
    depends_on:
      - postgis

  postgis:
    image: thiras/postgis
    build:
      context: docker-postgis/9.6-2.3
    links:
      - pgadmin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    user: postgres

  pgadmin:
    image: thiras/pgadmin4
    build:
      context: dockercloud-pgadmin4
    ports:
      - "5050:5050"
    volumes:
      - pga_data:/var/lib/pgadmin4

volumes:
  db_data:
  geo_data:
  pga_data:
