version: '3'

services:

  geoserver:
    image: thiras/geoserver
    build:
      context: docker-geoserver
      args:
        - ORACLE_JDk=true
    links:
      - postgis
    ports:
      - "8080:8080"
    volumes:
      - ./docker-geoserver/resources:/opt/geoserver/data_dir
    depends_on:
      - postgis

  postgis:
    image: mdillon/postgis
    volumes:
      - ./db:/var/lib/postgresql
    expose:
      - "5432"
    user: postgres

#  pgadmin:
#    image: fenglc/pgadmin4
