version: '3'

services:

  geoserver:
    image: thiras/geoserver
    build:
      context: docker-geoserver
      args:
        - ORACLE_JDk=true
    link:
      - postgis
    ports:
      - "8080:8080"
    volume:
      - ./docker-geoserver/resources:/opt/geoserver/data_dir

  postgis:
    image: mdillon/postgis
    volume:
      - ./db:/var/lib/postgresql

#  pgadmin:
#    image: fenglc/pgadmin4
