version: '3.2'

services:

  geoserver:
    image: thiras/geoserver
    build:
      context: docker-geoserver
      args:
        - ORACLE_JDk=true
    links:
      - postgis
    ports:
      - "8080:8080"
    volumes:
      - geo_data:/opt/geoserver/data_dir
    depends_on:
      - postgis

  postgis:
    image: thiras/postgis
    build:
      context: docker-postgis/9.6-2.3
    links:
      - pgadmin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    user: postgres

  pgadmin:
    image: fenglc/pgadmin4
    ports:
      - "5050:5050"

volumes:
  db_data:
  geo_data:
  # db_data:
    # volume:
      # nocopy: true
  # geo_data:
